name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    name: "Test Migration"
    runs-on: ubuntu-latest

    steps:
    - name: Install Quarkus CLI
      run: |
        curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
        curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio

    - run: /home/runner/.jbang/bin/quarkus --version
      shell: bash
