name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    name: "Test Migration"
    runs-on: ubuntu-latest

    steps:
    - name: Install Quarkus CLI
      uses: gastaldi/install-quarkus-cli-action@main

    - run: quarkus --version

