name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    name: "Test Migration"
    runs-on: ubuntu-latest

    steps:
    - uses: sdkman/sdkman-action@master
      id: sdkman
      with:
        candidate: quarkus
        version: 3.0.0.Beta1
    - run: quarkus --version
